runtime: java11
instance_class: B4_1G
manual_scaling:
  instances: 2
env_variables:
  SPRING_PROFILES_ACTIVE: cloud
  # REPLACE PROJECT_ID with your project ID!
  MESSAGES_ENDPOINT: https://guestbook-service-dot-qwiklabs-gcp-00-1509ab540162.appspot.com/guestbookMessages
